# Generated by Django 3.2.24 on 2024-03-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_order', '0006_alter_joborderimage_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joborderimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='joborderimage',
            name='uploaded_at',
        ),
    ]
