# Generated by Django 3.2.24 on 2024-03-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duration_minutes',
            new_name='duration_months',
        ),
    ]
