# Generated by Django 3.2.24 on 2024-03-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
    ]
